### ISSUE TITLE
usage_report distributor bails out if server side doesn't have stripe configuration

### ISSUE THREAD

**Issue by konstan** [nuvla/job-engine#107]
```
root@20200629T084206-worker-1:~# docker logs test_jobd-usage-report.1.rrlzkle3957nc1vn5fawiq36s
INFO:root:Action "stop_infrastructure_service_coe" registered
INFO:root:Action "reboot_nuvlabox" registered
INFO:root:Action "start_deployment" registered
INFO:root:Action "deployment_state" registered
INFO:root:Action "credential_check" registered
INFO:root:Action "cleanup_jobs" registered
INFO:root:Action "dummy_test_action" registered
INFO:root:Action "check_nuvlabox_api" registered
INFO:root:Action "start_infrastructure_service_coe" registered
INFO:root:Action "fetch_deployment_log" registered
INFO:root:Action "enable-stream" registered
INFO:root:Action "usage_report" registered
INFO:root:Action "decommission_nuvlabox" registered
INFO:root:Action "disable-stream" registered
INFO:root:Action "update_nuvlabox_releases" registered
INFO:root:Action "stop_deployment" registered
INFO:root:Action "component_image_state" registered
INFO:root:Action "service_image_state" registered
INFO:root:Action "validate-docker-compose" registered
INFO:root:Action "update_deployment" registered
2020-06-29 14:39:46,299 - INFO - distributor.py:47 - I am distributor Randy.
2020-06-29 14:39:46,300 - INFO - distributor.py:33 - STARTING ELECTION
2020-06-29 14:39:46,306 - INFO - distributor.py:16 - I am Randy and I have been elected to distribute "usage_report" jobs
2020-06-29 14:39:46,331 - ERROR - base.py:118 - server configuration for stripe is missing
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nuvla/api/api.py", line 403, in _cimi_request
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://api:8200/api/customer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nuvla/job/base.py", line 116, in main
    command().execute()
  File "/usr/local/lib/python3.8/site-packages/nuvla/job/base.py", line 108, in execute
    self.do_work()
  File "/usr/local/lib/python3.8/site-packages/nuvla/job/distributor.py", line 48, in do_work
    self._start_distribution()
  File "/usr/local/lib/python3.8/site-packages/nuvla/job/distributor.py", line 34, in _start_distribution
    election.run(self._job_distributor)
  File "/usr/local/lib/python3.8/site-packages/kazoo/recipe/election.py", line 54, in run
    func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nuvla/job/distributor.py", line 19, in _job_distributor
    for cimi_job in self.job_generator():
  File "/app/job_distributor_usage_report.py", line 36, in job_generator
    for customer in self.customers():
  File "/app/job_distributor_usage_report.py", line 24, in customers
    return self.api.search('customer', select='id, parent, customer-id').resources
  File "/usr/local/lib/python3.8/site-packages/nuvla/api/api.py", line 550, in search
    resp_json = self._cimi_put(resource_type=resource_type, data=kwargs)
  File "/usr/local/lib/python3.8/site-packages/nuvla/api/api.py", line 430, in _cimi_put
    return self._cimi_request('PUT', uri, params=params, json=json, data=data)
  File "/usr/local/lib/python3.8/site-packages/nuvla/api/api.py", line 416, in _cimi_request
    raise NuvlaError(message, response)
nuvla.api.api.NuvlaError: server configuration for stripe is missing
root@20200629T084206-worker-1:~#
```

**Comment by 0xbase12** [comment]
Yes, this service is optional. Probably admin has to add it manually if he want pricing. I think I'll remove it from deployment.

**Comment by konstan** [comment]
OK. But what I mean is, this app in the container should not bail out if it finds that something is missing somewhere. I.e. because nuvla api throws on server errors, this `File "/app/job_distributor_usage_report.py", line 24, in customers` should just catch the exception and log it, allowing for the app to continue. I'll add this now.

**Comment by 0xbase12** [comment]
Yes, I agree with you
