### ISSUE TITLE
floating IPs attachment from a pool in openstack driver doesn't work with COE provisioning framework

### ISSUE THREAD

**Issue by konstan** [nuvla/job-engine#213]
openstack driver with the dynamic attachment of floating IPs from a pool is not compatible with COE provisioning framework that attempts to parallelize the provisioning of VMs.

As the result, public floating IPs are not assigned to all VMs, which is required to complete the installation of the COE cluster.

Possible solutions:
A. make the provisioning sequential in the case the requested driver is openstack
B. retry on this specific error 

```
drwxr-xr-x   4 konstan  staff   128 Oct 13 17:12 cluster-openstack
2021-10-18 06:40:36,734 - ERROR - executor.py:91 - Failed to process job/5cc4f4b5-c739-4ed7-9911-e5583dd2d215, with error: RuntimeError-multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/usr/local/lib/python3.10/site-packages/nuvla/connector/docker_machine_connector.py", line 372, in _start_machine
    err_code = machine.create(machine_name, driver=driver_name,
  File "/usr/local/lib/python3.10/site-packages/nuvla/connector/machine/machine.py", line 114, in create
    stdout, stderr, errorcode = self._run(cmd, env_extra=env, blocking=blocking, machine_name=name)
  File "/usr/local/lib/python3.10/site-packages/nuvla/connector/machine/machine.py", line 64, in _run
    raise RuntimeError(f"cmd returned error {error_code}: {stderr.decode('utf-8').strip()}")
RuntimeError: cmd returned error 1: Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/nuvla/job/executor/executor.py", line 70, in _process_jobs
    return_code = action_instance.do_work()
  File "/usr/local/lib/python3.10/site-packages/nuvla/job/actions/coe_provision.py", line 114, in do_work
    return self.provision_coe()
  File "/usr/local/lib/python3.10/site-packages/nuvla/job/actions/coe_provision.py", line 105, in provision_coe
    self._provision_coe(infra_service)
  File "/usr/local/lib/python3.10/site-packages/nuvla/job/actions/coe_provision.py", line 45, in _provision_coe
    result = coe.provision(coe_custer_params)
  File "/usr/local/lib/python3.10/site-packages/nuvla/connector/connector.py", line 15, in wrapper
    raise e
  File "/usr/local/lib/python3.10/site-packages/nuvla/connector/connector.py", line 13, in wrapper
    result = f(self, *f_args, **f_kwargs)
  File "/usr/local/lib/python3.10/site-packages/nuvla/connector/docker_machine_connector.py", line 661, in provision
    raise ex
  File "/usr/local/lib/python3.10/site-packages/nuvla/connector/docker_machine_connector.py", line 642, in provision
    self._provision_cluster(nodes, inventory)
  File "/usr/local/lib/python3.10/site-packages/nuvla/connector/docker_machine_connector.py", line 498, in _provision_cluster
    raise ex
  File "/usr/local/lib/python3.10/site-packages/nuvla/connector/docker_machine_connector.py", line 486, in _provision_cluster
    err_codes = pool.starmap(self._start_machine, inputs)
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
RuntimeError: cmd returned error 1: Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
```

**Comment by konstan** [comment]
Yes.

**Comment by konstan** [comment]
A. option to be implemented.

The midterm plan is migration to terraform https://github.com/nuvla/job-engine/issues/187
