### ISSUE TITLE
Reboot job does not work after helm upgrade

### ISSUE THREAD

**Issue by amitbhanja** [nuvla/job-engine#296]
This is run in raspberry pi
Steps to reproduce:

1. helm install nuvlaedge-$UUID nuvlaedge/nuvlaedge --version $VERSION --set NUVLAEDGE_UUID=nuvlabox/$UUID --set vpnClient=true --set kubernetesNode=$HOSTNAME
2. Now if we upgrade to a certain branch.
    helm upgrade nuvlaedge-$UUID nuvlaedge/nuvlaedge --version $VERSION --set NUVLAEDGE_UUID=nuvlabox/$UUID --set vpnClient=true --set kubernetesNode=$HOSTNAME --set NUVLAEDGE_JOB_ENGINE_LITE_IMAGE=nuvladev/job-lite:<branch-name>

3. Reboot is done through nuvla.io page.
4. We see error in the nuvla page
Job reboot_nuvlabox failed
from server for: "/tmp/tmp5rbavj9o/reboot_job_manifest.yaml": jobs.batch "reboot-nuvlaedge" is forbidden: User "nuvla" cannot get resource "jobs" in API group "batch" in the namespace "nuvlaedge-a5aa3626-8a65-4f56-a2cb-90822cff7daa"

5. Logs collected from the job created

2023-10-18 08:32:03,693 - INFO - executor.py:111 - I am executor Kenny.
2023-10-18 08:32:03,823 - INFO - executor.py:67 - Got new job/60ea5bd6-83c1-47c0-bebd-c0f7554dc55c.
2023-10-18 08:32:03,879 - INFO - nuvlabox_reboot.py:20 - Rebooting NuvlaEdge nuvlabox/a5aa3626-8a65-4f56-a2cb-90822cff7daa
2023-10-18 08:32:03,879 - INFO - nuvlabox_reboot.py:23 - Found kubernetes installation.
2023-10-18 08:32:03,879 - INFO - kubernetes.py:564 - Running the new job-lite image.... JSW
2023-10-18 08:32:03,941 - INFO - kubernetes.py:74 - Connecting to endpoint: https://10.43.0.1:443
2023-10-18 08:32:03,944 - INFO - kubernetes.py:590 - Using image: sixsq/nuvlaedge:latest
2023-10-18 08:32:05,165 - ERROR - utils.py:79 - CompletedProcess(args=['kubectl', '-s', 'https://10.43.0.1:443', '--client-certificate', '/tmp/tmpgkd1gv9s', '--client-key', '/tmp/tmpwufw97_l', '--certificate-authority', '/tmp/tmp530dk8qm', 'apply', '-f', '/tmp/tmp5rbavj9o/reboot_job_manifest.yaml'], returncode=1, stdout='', stderr='Error from server (Forbidden): error when retrieving current configuration of:\nResource: "batch/v1, Resource=jobs", GroupVersionKind: "batch/v1, Kind=Job"\nName: "reboot-nuvlaedge", Namespace: "nuvlaedge-a5aa3626-8a65-4f56-a2cb-90822cff7daa"\nfrom server for: "/tmp/tmp5rbavj9o/reboot_job_manifest.yaml": jobs.batch "reboot-nuvlaedge" is forbidden: User "nuvla" cannot get resource "jobs" in API group "batch" in the namespace "nuvlaedge-a5aa3626-8a65-4f56-a2cb-90822cff7daa"\n')
NoneType: None
2023-10-18 08:32:05,344 - INFO - job.py:220 - Reached final state: job/60ea5bd6-83c1-47c0-bebd-c0f7554dc55c removed from queue.
2023-10-18 08:32:05,344 - ERROR - executor.py:93 - Failed to process job/60ea5bd6-83c1-47c0-bebd-c0f7554dc55c, with error: Exception-Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/nuvla/job/executor/executor.py", line 72, in _process_jobs
    return_code = action_instance.do_work()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nuvla/job/actions/nuvlabox_reboot.py", line 46, in do_work
    return self.reboot()
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nuvla/job/actions/nuvlabox_reboot.py", line 24, in reboot
    ret = self._reboot_k8s()
          ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nuvla/job/actions/nuvlabox_reboot.py", line 41, in _reboot_k8s
    ret = connector.reboot()
          ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nuvla/connector/connector.py", line 15, in wrapper
    raise e
  File "/usr/local/lib/python3.11/site-packages/nuvla/connector/connector.py", line 13, in wrapper
    result = f(self, *f_args, **f_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nuvla/connector/kubernetes.py", line 634, in reboot
    reboot_result = execute_cmd(kubectl_cmd_reboot)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nuvla/connector/utils.py", line 80, in execute_cmd
    raise Exception(result.stderr)
Exception: Error from server (Forbidden): error when retrieving current configuration of:
Resource: "batch/v1, Resource=jobs", GroupVersionKind: "batch/v1, Kind=Job"
Name: "reboot-nuvlaedge", Namespace: "nuvlaedge-a5aa3626-8a65-4f56-a2cb-90822cff7daa"
from server for: "/tmp/tmp5rbavj9o/reboot_job_manifest.yaml": jobs.batch "reboot-nuvlaedge" is forbidden: User "nuvla" cannot get resource "jobs" in API group "batch" in the namespace "nuvlaedge-a5aa3626-8a65-4f56-a2cb-90822cff7daa"

2023-10-18 08:32:05,344 - INFO - executor.py:106 - Executor Kenny properly stopped.

**Comment by giovannibianco** [comment]
Here is a sequence that runs on exoscale VM that works:
```
export UUID=4f1fd73c-05ce-4d5a-8687-c14c7a358027
export VERSION=2.11.2
export HOSTNAME=`hostname -s`
helm repo update
helm install nuvlaedge-$UUID nuvlaedge/nuvlaedge --version $VERSION --set NUVLAEDGE_UUID=nuvlabox/$UUID --set vpnClient=true --set kubernetesNode=$HOSTNAME
helm upgrade nuvlaedge-$UUID nuvlaedge/nuvlaedge --version $VERSION --set NUVLAEDGE_UUID=nuvlabox/$UUID --set vpnClient=true --set kubernetesNode=$HOSTNAME --set NUVLAEDGE_JOB_ENGINE_LITE_IMAGE=nuvladev/job-lite:issue-294-reboot-fix
```
Tested the update and reboot...

- [ ] Update
- [ ] Reboot

I do note though an error in the system-manager:
```
Traceback (most recent call last):
  File "/usr/local/bin/system-manager", line 8, in <module>
    sys.exit(entry())
             ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nuvlaedge/system_manager/__init__.py", line 156, in entry
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nuvlaedge/system_manager/__init__.py", line 116, in main
    requirements_check(software_requirements, system_requirements, self_sup.operational_status)
  File "/usr/local/lib/python3.11/site-packages/nuvlaedge/system_manager/__init__.py", line 81, in requirements_check
    meet_hw_rq = system_rq.check_all_hw_requirements()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nuvlaedge/system_manager/requirements.py", line 102, in check_all_hw_requirements
    meets_ram_req = self.check_ram_requirements()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nuvlaedge/system_manager/requirements.py", line 67, in check_ram_requirements
    total_ram = round(self.coe_client.get_ram_capacity(), 2)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nuvlaedge/system_manager/common/coe_client.py", line 248, in get_ram_capacity
    return int(self.get_node_info().status.capacity.get('memory', '0').rstrip('Ki'))/1024
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '3918M'
```

**Comment by giovannibianco** [comment]
I think this issue can be closed as we have determined that the credentials in the k3s were causing the problem?

**Comment by amitbhanja** [comment]
Yes, we can close it now as it is tested with the new installation of k3s.
