### ISSUE TITLE
Fetching logs for k8s NuvlaEdge fails...

### ISSUE THREAD

**Issue by giovannibianco** [nuvla/job-engine#300]
When trying to retrieve logs for the overall NuvlaEdge (not the deployments running on it) we get the following error:

```
2023-08-16 10:17:03,358 - ERROR - resource_log_fetch.py:103 - Failed to fetch_nuvlabox_log resource-log/f0504c82-11e9-407f-a750-201b80bb62e3: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
2023-08-16 10:17:03,480 - INFO - job.py:217 - Reached final state: job/0090f1ae-0183-4c21-929e-b6592a42fce8 removed from queue.
2023-08-16 10:17:03,481 - ERROR - executor.py:91 - Failed to process job/0090f1ae-0183-4c21-929e-b6592a42fce8, with error: DockerException-Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/docker/transport/unixconn.py", line 27, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory
'''

etc etc...

Reproducible easily.

**Comment by giovannibianco** [comment]
Order of tasks:
- [x] Get the list of components running correctly from the original deployment https://github.com/nuvlaedge/nuvlaedge/issues/130
- [x] Get the list of components for the logs retrieval
- [ ] Get the logs

**Comment by giovannibianco** [comment]
Discovered an issue that will have to be solved... 
It is possible that a deployment can own more than one replicasets.
But only one of these will be valid and contain the pods that the logs are collected.
The assumption that a deployment only contains one replicaset is false... 
A deployment will have only one VALID and active replicaset.
Need to create a new function to return the active replicaset.
